# Generated by Django 3.1.3 on 2020-12-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20201201_1511'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ecrivain',
            table='ecrivains',
        ),
    ]
