# Generated by Django 3.1.3 on 2020-12-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20201201_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecrivain',
            name='name',
            field=models.CharField(help_text='Enter field name', max_length=40),
        ),
    ]
